# Generated by Django 5.0.6 on 2024-06-22 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 22, 18, 37, 55, 175993), verbose_name='Publishing Date'),
        ),
    ]
