# Generated by Django 5.0.6 on 2024-06-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 20, 2, 44, 749969), verbose_name='Publishing Date'),
        ),
    ]
